### ISSUE TITLE
x264 fails to compile with armv6, armv7 and sdk3.0 or sdk3.2

### ISSUE THREAD

**Issue by tiz** [gabriel/ffmpeg-iphone-build#1]
Hi,

First thanks for our scripts ^^ it's the holly grail !!

I've got this error when I run build-x264-armv6 and build-x264-armv7

/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc-4.2 -O3 -fno-fast-math  -Wall -I. --sysroot=/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS3.0.sdk -arch armv6 -falign-loops=16 -std=gnu99 -fPIC -s -fomit-frame-pointer   -c -o encoder/me.o encoder/me.c
encoder/me.c: In function ‘x264_me_search_ref’:
encoder/me.c:249: warning: passing argument 1 of ‘x264_predictor_roundclip’ from incompatible pointer type
encoder/me.c:253: warning: cast to pointer from integer of different size
encoder/me.c:255: error: subscripted value is neither array nor pointer
encoder/me.c:256: error: subscripted value is neither array nor pointer
encoder/me.c:264: error: subscripted value is neither array nor pointer
encoder/me.c:265: error: subscripted value is neither array nor pointer
make: **\* [encoder/me.o] Error 1
Installed: x264-armv6/dist

I think it's more a bug from x264 sources I check out. But it works for i386

Tiz

**Comment by tiz** [comment]
SOLVED:

The problem comes from the last revision of x264.

I'm new in git usage but with a

"git checkout f6114408330c1f1c5bb897ab74258f9972cc9bf9" in x264-armv6 solved the problem and compilation passed

Tiz
